-- Fix missing columns for KYC Step 2
ALTER TABLE drivers 
ADD COLUMN IF NOT EXISTS city VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS postal_code VARCHAR(10) NULL,
ADD COLUMN IF NOT EXISTS license_issue_date DATE NULL,
ADD COLUMN IF NOT EXISTS years_of_experience INT NULL,
ADD COLUMN IF NOT EXISTS previous_company VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS bank_id BIGINT UNSIGNED NULL,
ADD COLUMN IF NOT EXISTS account_number VARCHAR(20) NULL,
ADD COLUMN IF NOT EXISTS account_name VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS bvn VARCHAR(11) NULL,
ADD COLUMN IF NOT EXISTS residential_address TEXT NULL,
ADD COLUMN IF NOT EXISTS has_vehicle BOOLEAN NULL,
ADD COLUMN IF NOT EXISTS vehicle_type VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS vehicle_year INT NULL,
ADD COLUMN IF NOT EXISTS preferred_work_location VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS available_for_night_shifts BOOLEAN NULL,
ADD COLUMN IF NOT EXISTS available_for_weekend_work BOOLEAN NULL;